exposee_mattfeld_azimi.pdf: exposee_mattfeld_azimi.tex literatur.bib
	pdflatex exposee_mattfeld_azimi
	bibtex exposee_mattfeld_azimi
	pdflatex exposee_mattfeld_azimi
	pdflatex exposee_mattfeld_azimi

clean:
	rm -f *.bbl *.blg *.out *.aux *.log abstract.pdf lrec2014.pdf
